/** @type {import('tailwindcss').Config} */
import { nextui } from "@nextui-org/theme";
import typography from "@tailwindcss/typography";
import { fontFamily } from "tailwindcss/defaultTheme";
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    container: {
      screens: {
        xl: "1280px",
      },
    },
    extend: {
      boxShadow: {
        "bento-shadow": "var(--bento-shadow)",
      },
      colors: {
        "base-color": "var(--color-base)",
        "base-color-h": "var(--color-base-h)",
        "base-color-m": "var(--color-base-m)",
        "base-color-d": "var(--color-base-d)",
        "base-color-dark": "var(--color-base-dark)",
        "base-color-dark-h": "var(--color-base-dark-h)",
        "base-color-dark-m": "var(--color-base-dark-m)",
        "base-color-dark-d": "var(--color-base-dark-d)",
        "base-dark": "var(--background-dark)",
        "base-dark-90": "var(--background-dark-90)",
        "base-dark-80": "var(--background-dark-80)",
        "base-dark-70": "var(--background-dark-70)",
        "base-dark-60": "var(--background-dark-60)",
        "base-dark-50": "var(--background-dark-50)",
        "base-dark-40": "var(--background-dark-40)",
        "base-dark-30": "var(--background-dark-30)",
        "base-dark-20": "var(--background-dark-20)",
        "base-dark-10": "var(--background-dark-10)",
        "base-full-dark": "var(--background-dark-f)",
        "base-full-dark-90": "var(--background-dark-f-90)",
        "base-full-dark-80": "var(--background-dark-f-80)",
        "base-full-dark-70": "var(--background-dark-f-70)",
        "base-full-dark-60": "var(--background-dark-f-60)",
        "base-full-dark-50": "var(--background-dark-f-50)",
        "base-full-dark-40": "var(--background-dark-f-40)",
        "base-full-dark-30": "var(--background-dark-f-30)",
        "base-full-dark-20": "var(--background-dark-f-20)",
        "base-full-dark-10": "var(--background-dark-f-10)",
        "radical-red": {
          50: "#ffeff1",
          100: "#ffe0e6",
          200: "#ffc6d3",
          300: "#ff97ae",
          400: "#ff5d83",
          500: "#ff245e",
          600: "#ff004d",
          700: "#d70041",
          800: "#b4003f",
          900: "#99023c",
          950: "#57001b",
        },
        broom: {
          50: "#fdfee8",
          100: "#fcffc2",
          200: "#fcff87",
          300: "#fffc43",
          400: "#fff024",
          500: "#efd503",
          600: "#cea700",
          700: "#a47804",
          800: "#885e0b",
          900: "#734c10",
          950: "#432805",
        },
        bittersweet: {
          50: "#fef3f2",
          100: "#fee5e2",
          200: "#ffcfc9",
          300: "#fdada4",
          400: "#fa8072",
          500: "#f15442",
          600: "#df3623",
          700: "#bb2b1a",
          800: "#9b2619",
          900: "#80261c",
          950: "#460f09",
        },
        orient: {
          50: "#e7fffd",
          100: "#c2fffb",
          200: "#8cfff7",
          300: "#3dfff2",
          400: "#00ffee",
          500: "#00f2ff",
          600: "#00bfe3",
          700: "#0096b5",
          800: "#007690",
          900: "#00627b",
          950: "#004055",
        },
        "cerise-red": {
          50: "#fdf3f4",
          100: "#fce7eb",
          200: "#f8d3db",
          300: "#f2afbc",
          400: "#ea8299",
          500: "#da4167",
          600: "#c93560",
          700: "#a92751",
          800: "#8e2349",
          900: "#7a2143",
          950: "#430e21",
        },
        midnight: {
          50: "#ecfaff",
          100: "#d4f2ff",
          200: "#b2e9ff",
          300: "#7ddeff",
          400: "#41c8ff",
          500: "#15a8ff",
          600: "#0087ff",
          700: "#006ffe",
          800: "#0059cd",
          900: "#084da0",
          950: "#061b37",
        },
      },
      fontFamily: {
        grotesk: ["var(--font-space-grotesk)", ...fontFamily.sans],
        motivasans: ["var(--font-motiva-sans)", ...fontFamily.sans],
        spacemono: ["var(--font-space-mono)", ...fontFamily.mono],
        dmsans: ["var(--font-dm-sans)", ...fontFamily.sans],
      },
      backgroundImage: {
        noise: "url(/extras/noise.webp)",
        "landing-gradient": "var(--landing-gradient)",
        "bento-gradient": "var(--bg-bento-gradient)",
        "light-gradient": "var(--light-gradient)",
        "light-gradient-v2": "var(--light-gradient-v2)",
        "dark-gradient": "var(--dark-gradient)",
        "dark-gradient-v2": "var(--dark-gradient-v2)",
        "light-radial-gradient": "var(--light-radial-gradient)",
        "dark-radial-gradient": "var(--dark-radial-gradient)",
        "dark-radial-gradient-2": "var(--dark-radial-gradient-2)",
        "resource-1": "var(--bg-resource-1)",
        "resource-2": "var(--bg-resource-2)",
        "resource-3": "var(--bg-resource-3)",
        "resource-4": "var(--bg-resource-4)",
        "resource-5": "var(--bg-resource-5)",
        "resource-6": "var(--bg-resource-6)",
      },
      animation: {
        "shine-infinite": "shine 2s ease-in-out infinite",
      },
      keyframes: {
        shine: {
          "0%": { transform: "skew(-12deg) translateX(-100%)" },
          "100%": { transform: "skew(-12deg) translateX(100%)" },
        },
      },
    },
  },
  safelist: [
    "md:col-span-3",
    "md:col-span-4",
    "md:col-span-5",
    "text-cerise-red-800",
    "dark:text-cerise-red-300",
    "font-medium",
    "dark:bg-base-full-dark",
    "dark:bg-base-dark",
    "before:bg-resource-1",
    "before:bg-resource-2",
    "before:bg-resource-3",
    "before:bg-resource-4",
    "before:bg-resource-5",
    "before:bg-resource-6",
    "after:bg-resource-1",
    "after:bg-resource-2",
    "after:bg-resource-3",
    "after:bg-resource-4",
    "after:bg-resource-5",
    "after:bg-resource-6",
    "space-y-6",
    "space-y-2",
    "pl-5",
    "!mt-2",
  ],
  plugins: [
    typography,
    nextui({
      themes: {
        light: {
          colors: {
            danger: {
              50: "#fef3f2",
              100: "#fee5e2",
              200: "#ffcfc9",
              300: "#fdada4",
              400: "#fa8072",
              500: "#f15442",
              600: "#df3623",
              700: "#bb2b1a",
              800: "#9b2619",
              900: "#80261c",
              DEFAULT: "#fa8072",
            },
            default: {
              50: "#F9FAFB",
              100: "#F3F4F6",
              200: "#E5E7EB",
              300: "#D1D5DB",
              400: "#9CA3AF",
              500: "#6B7280",
              600: "#4B5563",
              700: "#374151",
              800: "#1F2937",
              900: "#111827",
              DEFAULT: "#E5E7EB",
            },
          },
        },
        dark: {
          colors: {
            danger: {
              50: "#fdf3f4",
              100: "#fce7eb",
              200: "#f8d3db",
              300: "#f2afbc",
              400: "#ea8299",
              500: "#da4167",
              600: "#c93560",
              700: "#a92751",
              800: "#8e2349",
              900: "#7a2143",
              DEFAULT: "#c93560",
            },
          },
        },
      },
    }),
  ],
};
export default config;
