/** @type {import('tailwindcss').Config} */
import { nextui } from "@nextui-org/theme";
import typography from "@tailwindcss/typography";
import { fontFamily } from "tailwindcss/defaultTheme";
import animate from "tailwindcss-animate";

import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ["class"],
  theme: {
    container: {
      screens: {
        xl: "1280px",
      },
    },
    extend: {
      boxShadow: {
        "bento-shadow": "var(--bento-shadow)",
      },
      colors: {
        main: "var(--text-main)",
        "main-h": "var(--text-main-h)",
        "main-m": "var(--text-main-m)",
        "main-l": "var(--text-main-l)",
        "main-dark": "var(--text-main-dark)",
        "main-dark-h": "var(--text-main-dark-h)",
        "main-dark-m": "var(--text-main-dark-m)",
        "main-dark-l": "var(--text-main-dark-l)",
        dark: "var(--background-dark)",
        "dark/90": "var(--background-dark-90)",
        "dark/80": "var(--background-dark-80)",
        "dark/70": "var(--background-dark-70)",
        "dark/60": "var(--background-dark-60)",
        "dark/50": "var(--background-dark-50)",
        "dark/40": "var(--background-dark-40)",
        "dark/30": "var(--background-dark-30)",
        "dark/20": "var(--background-dark-20)",
        "dark/10": "var(--background-dark-10)",
        "full-dark": "var(--background-dark-f)",
        "full-dark/90": "var(--background-dark-f-90)",
        "full-dark/80": "var(--background-dark-f-80)",
        "full-dark/70": "var(--background-dark-f-70)",
        "full-dark/60": "var(--background-dark-f-60)",
        "full-dark/50": "var(--background-dark-f-50)",
        "full-dark/40": "var(--background-dark-f-40)",
        "full-dark/30": "var(--background-dark-f-30)",
        "full-dark/20": "var(--background-dark-f-20)",
        "full-dark/10": "var(--background-dark-f-10)",
        "accent-dark": "var(--background-accent-dark)",
        altern: "var(--background-alternative)",
        "altern-light": "var(--background-alternative-light)",
        "altern-accent": "var(--background-alternative-accent)",
        "radical-red": {
          "50": "#ffeff1",
          "100": "#ffe0e6",
          "200": "#ffc6d3",
          "300": "#ff97ae",
          "400": "#ff5d83",
          "500": "#ff245e",
          "600": "#ff004d",
          "700": "#d70041",
          "800": "#b4003f",
          "900": "#99023c",
          "950": "#57001b",
        },
        broom: {
          "50": "#fdfee8",
          "100": "#fcffc2",
          "200": "#fcff87",
          "300": "#fffc43",
          "400": "#fff024",
          "500": "#efd503",
          "600": "#cea700",
          "700": "#a47804",
          "800": "#885e0b",
          "900": "#734c10",
          "950": "#432805",
        },
        bittersweet: {
          "50": "#fef3f2",
          "100": "#fee5e2",
          "200": "#ffcfc9",
          "300": "#fdada4",
          "400": "#fa8072",
          "500": "#f15442",
          "600": "#df3623",
          "700": "#bb2b1a",
          "800": "#9b2619",
          "900": "#80261c",
          "950": "#460f09",
        },
        orient: {
          "50": "#e7fffd",
          "100": "#c2fffb",
          "200": "#8cfff7",
          "300": "#3dfff2",
          "400": "#00ffee",
          "500": "#00f2ff",
          "600": "#00bfe3",
          "700": "#0096b5",
          "800": "#007690",
          "900": "#00627b",
          "950": "#004055",
        },
        "cerise-red": {
          "50": "#fdf3f4",
          "100": "#fce7eb",
          "200": "#f8d3db",
          "300": "#f2afbc",
          "400": "#ea8299",
          "500": "#da4167",
          "600": "#c93560",
          "700": "#a92751",
          "800": "#8e2349",
          "900": "#7a2143",
          "950": "#430e21",
        },
        midnight: {
          "50": "#ecfaff",
          "100": "#d4f2ff",
          "200": "#b2e9ff",
          "300": "#7ddeff",
          "400": "#41c8ff",
          "500": "#15a8ff",
          "600": "#0087ff",
          "700": "#006ffe",
          "800": "#0059cd",
          "900": "#084da0",
          "950": "#061b37",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        grotesk: ["var(--font-space-grotesk)", ...fontFamily.sans],
        motivasans: ["var(--font-motiva-sans)", ...fontFamily.sans],
        spacemono: ["var(--font-space-mono)", ...fontFamily.mono],
        dmsans: ["var(--font-dm-sans)", ...fontFamily.sans],
        sans: ["var(--font-geist-sans)"],
      },
      fontSize: {
        xxs: "0.625rem",
      },
      backgroundImage: {
        noise: "url(/extras/noise.webp)",
        "landing-gradient": "var(--landing-gradient)",
        "bento-gradient": "var(--bg-bento-gradient)",
        "light-gradient": "var(--light-gradient)",
        "light-gradient-v2": "var(--light-gradient-v2)",
        "dark-gradient": "var(--dark-gradient)",
        "dark-gradient-v2": "var(--dark-gradient-v2)",
        "light-radial-gradient": "var(--light-radial-gradient)",
        "dark-radial-gradient": "var(--dark-radial-gradient)",
        "dark-radial-gradient-2": "var(--dark-radial-gradient-2)",
      },
      transitionDuration: {
        "2000": "2000ms",
      },
      animation: {
        "shine-infinite": "shine 2s ease-in-out infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      keyframes: {
        shine: {
          "0%": {
            transform: "skew(-12deg) translateX(-100%)",
          },
          "100%": {
            transform: "skew(-12deg) translateX(100%)",
          },
        },
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      maxWidth: {
        "8xl": "88rem",
      },
    },
  },
  safelist: [
    "md:col-span-3",
    "md:col-span-4",
    "md:col-span-5",
    "text-cerise-red-800",
    "dark:text-cerise-red-300",
    "font-medium",
    "dark:bg-full-dark",
    "dark:bg-dark",
    "space-y-6",
    "space-y-2",
    "pl-5",
    "!mt-2",
  ],
  plugins: [
    animate,
    typography,
    nextui({
      themes: {
        light: {
          colors: {
            danger: {
              50: "#fef3f2",
              100: "#fee5e2",
              200: "#ffcfc9",
              300: "#fdada4",
              400: "#fa8072",
              500: "#f15442",
              600: "#df3623",
              700: "#bb2b1a",
              800: "#9b2619",
              900: "#80261c",
              DEFAULT: "#fa8072",
            },
            default: {
              50: "#F9FAFB",
              100: "#F3F4F6",
              200: "#E5E7EB",
              300: "#D1D5DB",
              400: "#9CA3AF",
              500: "#6B7280",
              600: "#4B5563",
              700: "#374151",
              800: "#1F2937",
              900: "#111827",
              DEFAULT: "#E5E7EB",
            },
          },
        },
        dark: {
          colors: {
            danger: {
              50: "#fdf3f4",
              100: "#fce7eb",
              200: "#f8d3db",
              300: "#f2afbc",
              400: "#ea8299",
              500: "#da4167",
              600: "#c93560",
              700: "#a92751",
              800: "#8e2349",
              900: "#7a2143",
              DEFAULT: "#c93560",
            },
          },
        },
      },
    }),
  ],
};
export default config;
