export const searchStyles = {
  buttonCommon: [
    "group",
    "justify-between",
    "inline-flex",
    "items-center",
    "h-auto",
    "min-h-10",
    "px-2",
    "rounded-md",
    "text-start",
    "hover:bg-gray-200",
    "dark:hover:bg-dark",
    "focus:bg-gray-200",
    "dark:focus:bg-dark",
    "active:bg-gray-200",
    "dark:active:bg-dark",
    "!transition-none",
  ],
  dataText: [
    "group-hover:text-main dark:group-hover:text-main-dark",
    "group-focus:text-main dark:group-focus:text-main-dark",
    "group-active:text-main dark:group-active:text-main-dark",
  ],
  buttonTextColor: ["text-main-m", "dark:text-main-dark-m"],
  icon: ["size-5", "text-main-l", "dark:text-main-dark-l"],
  inputWrapper: [
    "inline-flex",
    "items-center",
    "w-full",
    "h-14",
    "bg-transparent",
    "text-main-h",
    "dark:text-main-dark-h",
    "shadow-none",
    "px-2",
    "hover:bg-transparent",
    "active:bg-transparent",
  ],
  input: [
    "focus-visible:ring-0 border-none",
    "!pr-8 md:text-base",
    "h-full",
    "shadow-none",
  ],
  clearButton: [
    "size-8 shrink-0",
    "hover:bg-gray-100 dark:hover:bg-full-dark/50",
    "transition-colors duration-150",
  ],
  modalHeader: ["flex", "items-center", "w-full", "pl-2", "pr-4", "!mt-0"],
  modalContent: ["p-2", "overflow-y-auto", "md:max-h-[50vh]"],
  noResults: [
    "flex",
    "flex-col",
    "text-center",
    "items-center",
    "justify-center",
    "h-32",
  ],
};
