export const searchStyles = {
  buttonCommon: [
    "group",
    "justify-between",
    "inline-flex",
    "items-center",
    "h-auto",
    "min-h-10",
    "px-2",
    "rounded-md",
    "text-start",
    "hover:bg-accent",
    "focus:bg-accent",
    "active:bg-accent",
    "transition-none!",
  ],
  dataText: [
    "group-hover:text-foreground",
    "group-focus:text-foreground",
    "group-active:text-foreground",
  ],
  buttonTextColor: ["text-muted-foreground"],
  icon: ["text-muted-foreground"],
  inputWrapper: ["flex items-center px-4"],
  input: [
    "focus-visible:ring-0 border-none w-full will-change-transform",
    "px-0 pr-4 py-3 text-sm",
    "h-12!",
    "shadow-none",
  ],
  clearButton: [
    "shrink-0 size-7",
    "hover:bg-transparent dark:hover:bg-transparent",
  ],
  modalHeader: ["flex", "items-center", "w-full", "px-1", "mt-0!"],
  modalContent: ["p-2", "overflow-y-auto"],
  noResults: [
    "flex",
    "flex-col",
    "text-center",
    "items-center",
    "justify-center",
    "h-32",
  ],
};
